### ISSUE TITLE
No feature list

### ISSUE THREAD

**Issue by guysoft** [speedy-net/speedy-net#1]
Hey,
Can you add a sentence about what the goal of this software is and its list of features?
I had to google speedy net, find the domain, and run a who-is to figure out you own speedy.net and understand this is some form of social network.

**Comment by uri-rodberg** [comment]
Hi Guy,

Everything is written in the specification. You can find the specifications
in the specifications folder on GitHub. Where do you expect the goal of
this software is and its list of features to be written? Please send me a
link.

Thanks,
Uri.

_Uri Even-Chen_
[image: photo] Phone: +972-54-3995700
Email: uri@speedy.net
Website: http://www.speedysoftware.com/uri/en/
http://www.facebook.com/urievenchen  http://plus.google.com/+urievenchen
  http://www.linkedin.com/in/urievenchen  http://twitter.com/urievenchen

**Comment by guysoft** [comment]
Those are technical specifications. It explains what fields should be in the database, how things should be programmed, etc. Thats not a feature list.

A a feature lists is an overview of a project with a explanation to a non-technical user what the system supports. 

For example:
https://diasporafoundation.org/
There is a clear list of what they provide.

Or:
https://github.com/ushahidi/platform

There is a clear explanation at the top of what it is.

**Comment by uri-rodberg** [comment]
Hi Guy,

OK, we will try to add a feature list. Thank you for the feedback.

Thanks,
Uri.

_Uri Even-Chen_
[image: photo] Phone: +972-54-3995700
Email: uri@speedy.net
Website: http://www.speedysoftware.com/uri/en/
http://www.facebook.com/urievenchen  http://plus.google.com/+urievenchen
  http://www.linkedin.com/in/urievenchen  http://twitter.com/urievenchen

**Comment by uri-rodberg** [comment]
Hi,

I added a feature list to the README file.

Thanks,
Uri.
